apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pfphd4hzx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pfphd4hzx-go 
  name: pfphd4hzx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pfphd4hzx-go 
